language: node_js

node_js:
  - "node"

services:
  - docker

env:
  - PGHOST=172.17.0.1 PGUSER=rs PGDATABASE=rs PGPASSWORD=123123 PGPORT=5432

before_install:
  - docker run --name rs-postgres -p 5432 -e POSTGRES_PASSWORD=123123 -e POSTGRES_USER=rs -e POSTGRES_DB=rs -d mdillon/postgis:11-alpine # postgis at your service

before_script:
  - node query.js # builds database tables
