language: node_js

node_js:
  - "node"

services:
  - docker

before_install:
  - cp .env.example .env # provides basic configuration
  - docker run --name rs-postgres -p 5432 -e POSTGRES_PASSWORD=123123 -e POSTGRES_USER=rs -e POSTGRES_DB=rs -d mdillon/postgis:11-alpine # postgis at your service

before_script:
  - node query.js # builds database tables
