language: node_js

node_js:
  - "node"

services:
  - docker

before_install:
  # shutdowns the system postgresql
  - sudo service postgresql stop
  # waits for postgresql to shutdown
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

  # provides basic configuration
  - cp .env.example .env
  # postgis at your service
  - docker run --name rs-postgres -p 5432:5432 -e POSTGRES_PASSWORD=123123 -e POSTGRES_USER=rs -e POSTGRES_DB=rs -d mdillon/postgis:11-alpine

before_script:
  - node query.js # builds database tables
